### ISSUE TITLE
Users Upload list failing (json)

### ISSUE THREAD

**Issue by f1nch** [dreamfactorysoftware/df-admin-interface#108]
https://github.com/dreamfactorysoftware/df-admin-interface/blob/a41d34bf1d5f9b4c5ab71fc6dacd1ba0480fd2d5/src/app/adf-users/df-manage-users/df-manage-users-table.component.ts#L76C8-L76C8

Error (code 1000): "Invalid data supplied. The username has already been taken."

http://localhost:4200/api/v2/system/user
payload = [
    {
        "id": 2,
        "name": "testUser1",
        "username": "user@email.com",
        "ldap_username": null,
        "first_name": null,
        "last_name": null,
        "last_login_date": null,
        "email": "user@email.com",
        "is_active": true,
        "phone": null,
        "security_question": null,
        "default_app_id": null,
        "adldap": null,
        "oauth_provider": null,
        "saml": null,
        "created_date": "2023-10-05T17:49:41.000000Z",
        "last_modified_date": "2023-10-05T17:56:22.000000Z",
        "created_by_id": 1,
        "last_modified_by_id": 1,
        "is_root_admin": 0,
        "confirmed": true,
        "expired": false
    },
    {
        "id": 3,
        "name": "testUser2",
        "username": "user2@email.com",
        "ldap_username": null,
        "first_name": null,
        "last_name": null,
        "last_login_date": null,
        "email": "user2@email.com",
        "is_active": true,
        "phone": null,
        "security_question": null,
        "default_app_id": null,
        "adldap": null,
        "oauth_provider": null,
        "saml": null,
        "is_root_admin": 0,
        "confirmed": true,
        "expired": false
    },
    {
        "id": 4,
        "name": "testUser3",
        "username": "user3@email.com",
        "ldap_username": null,
        "first_name": null,
        "last_name": null,
        "last_login_date": null,
        "email": "user3@email.com",
        "is_active": true,
        "phone": null,
        "security_question": null,
        "default_app_id": null,
        "adldap": null,
        "oauth_provider": null,
        "saml": null,
        "is_root_admin": 0,
        "confirmed": true,
        "expired": false
    }
]

**Comment by judgemavi** [comment]
error is because username already exist, if new users are provided it works ok
