### ISSUE TITLE
API Docs Casing Issue

### ISSUE THREAD

**Issue by thekevinm** [dreamfactorysoftware/df-admin-interface#131]
Within the API Docs tab the OpenAPI Spec is using capital naming conventions and with DF being case-sensitive, it is causing issues.

When invoking an API via the API Docs such as a Postgres DB, you will receive a 400 error `Resource 'Table' not found for service 'postgres'.`

The URL structure is `/api/v2/postgres/Table` when we want it to be all lowercase and contain the underscore no matter the request such as `/_schema`,` /_proc`, `/_func`.

**Comment by judgemavi** [comment]
@thekevinm fix has been pushed to dev, please confirm and close the issue

**Comment by thekevinm** [comment]
works great, thanks!
