### ISSUE TITLE
Using the built project inside DF app causes the auth screen to persist after login

### ISSUE THREAD

**Issue by anas-srikou** [dreamfactorysoftware/df-admin-interface#132]
I'm working on replacing the old UI with the new one.
<img width="1405" alt="Screenshot 2023-10-26 at 11 23 57" src="https://github.com/dreamfactorysoftware/df-admin-interface/assets/118708059/e8527c9e-03ab-42d0-9528-24f108360278">

Steps I did:

0- Checkout dev branch
1- I build the project using `npm run build` 
2- Copy the content of dist folder into DF public folder
3- Create an `index.blade.php` in the `resources/views` folder and copy the content of `index.html` into it
4- Update SplashController.php to return the view instead of redirecting to `dreamfactory/index.html`

<img width="591" alt="Screenshot 2023-10-26 at 11 22 19" src="https://github.com/dreamfactorysoftware/df-admin-interface/assets/118708059/6939cab4-d418-4a0e-afcc-eb1812f6e517">

If I try to refresh the page then it will get stuck on loading and calling the endpoint again and again
<img width="1371" alt="Screenshot 2023-10-26 at 11 26 17" src="https://github.com/dreamfactorysoftware/df-admin-interface/assets/118708059/69195b69-3604-4759-be04-aed862da01d9">

**Comment by judgemavi** [comment]
@anas-srikou a patch has been put in place, please test

**Comment by anas-srikou** [comment]
I tested the fix and it is working 🙏
