### ISSUE TITLE
Overhaul API Creation

### ISSUE THREAD

**Issue by thekevinm** [dreamfactorysoftware/df-admin-interface#159]
Rather than making the API creation process a lengthy form process, we can reformat the process.

1. When a user selects the + button to create a new API, rather than being thrown to the current API creation page to select the API type, they are presented with a grid containing the logos for each service.
2. Once they select the API they want from the grid they are asked to provide a name, label, description.
3. Lastly they are prompted to provide the connection details.

This can be broken into popups or the standard pages.

**Comment by Yi-Jacob** [comment]
@thekevinm I think we can close this?
