### ISSUE TITLE
Event Scripting not possible

### ISSUE THREAD

**Issue by thekevinm** [dreamfactorysoftware/df-admin-interface#180]
Under Event Scripts, APIs do not populate to allow for scripts to be attached as pre or post process events.

![Screenshot 2024-04-01 at 3 51 40 PM](https://github.com/dreamfactorysoftware/df-admin-interface/assets/36458555/709cb4b6-89e1-4fc6-ad6b-7c873853d372)

**Comment by Yi-Jacob** [comment]
https://github.com/dreamfactorysoftware/df-admin-interface/pull/181

Added the database here src/app/shared/components/df-script-editor/df-script-editor.component.ts for them to be included
