### ISSUE TITLE
Password Reset in Profile not functioning

### ISSUE THREAD

**Issue by thekevinm** [dreamfactorysoftware/df-admin-interface#198]
When updating the Password from the Profile page, the old password persists and is not changed. This functionality works under the Admins tab but not through the Profile page.

![Screenshot 2024-04-22 at 1 13 26 PM](https://github.com/dreamfactorysoftware/df-admin-interface/assets/36458555/2a331cc8-9a3d-464f-9e51-542fecb89fcd)

**Comment by Yi-Jacob** [comment]
https://github.com/dreamfactorysoftware/df-admin-interface/pull/201
