### ISSUE TITLE
API Docs URL encodes "*"

### ISSUE THREAD

**Issue by thekevinm** [dreamfactorysoftware/df-admin-interface#203]
For example if * is used as a related parameter in the API Docs it is auto-encoded.

![Screenshot 2024-04-29 at 2 55 05 PM](https://github.com/dreamfactorysoftware/df-admin-interface/assets/36458555/1eda21e1-1324-4c3e-9bd7-6375da33b6c9)

**Comment by Yi-Jacob** [comment]
#236
