### ISSUE TITLE
Failing tests for role details form

### ISSUE THREAD

**Issue by whenlin-rangle** [dreamfactorysoftware/df-admin-interface#46]
**Module/Component affected:**
`Df-role-details`

**Description**
For both create and edit mode, the respective test that checks if invalid input is **not** sent from the from is failing. Its suspected that there is no check for whether the form is valid or not

**Screenshot**
![Screenshot 2023-09-21 at 3 55 17 PM](https://github.com/dreamfactorysoftware/df-admin-interface/assets/122292164/ce3b2cf0-5371-4e40-80d6-996618f28660)

**Comment by f1nch** [comment]
fixed by: https://github.com/dreamfactorysoftware/df-admin-interface/pull/116
